name: 📄 Documentation Task
description: Add or improve documentation
title: "[Docs] "
labels: ["docs"]
assignees: []
body:
  - type: checkboxes
    id: documentation-area
    attributes:
      label: 📘 Area of documentation
      options:
        - label: README
        - label: CONTRIBUTING
        - label: Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 🧾 Description
      description: What needs to be documented or improved?
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: 📌 Additional Context
      description: Links to files or sections to update.
    validations:
      required: false
